### ISSUE TITLE
Does this work recursively?

### ISSUE THREAD

**Issue by mick-t** [smartfile/python-librsync#8]
Can I recursively rsync a directory using python-librsync? Will it accept a list of files names/directories to rsync (i.e. using rsync's --include-from=FILE  or --files-from=FILE  options).

Thanks! :)

**Comment by travcunn** [comment]
This is a really low level wrapper around librsync. If you want to calculate signatures/deltas for each file in your folder, you'll have to implement that yourself. You could use Python ```os.walk``` to traverse your directory structure and perform librsync operations on each file.

**Comment by mick-t** [comment]
That's what I was thinking. Thank you for the reply!
